



-- ==============================================================================
-- FAST CAMPUSVERSE: PHASE 2 QUERIES
-- 15 Functionalities covering all advanced SQL concepts
-- ==============================================================================

-- ==============================================================================
-- Q1. ONBOARDING A NEW STUDENT
-- Functionality: Register a new student into the system.
-- Concepts Covered: INSERT
-- ==============================================================================
INSERT INTO Students (roll_number, password_hash, full_name, current_balance) 
VALUES ('25L-5000', 'new_hash_xyz', 'Saad Qureshi', 0.00);
select * from Students;

-- ==============================================================================
-- Q2. PRICE INFLATION ADJUSTMENT
-- Functionality: Increase the price of Karak Chai due to inflation.
-- Concepts Covered: UPDATE, WHERE
-- ==============================================================================
UPDATE Cafeteria_Items 
SET price = 100.00 
WHERE item_name = 'Karak Chai';
select * from "Cafeteria_Items";

-- ==============================================================================
-- Q3. FRAUD PREVENTION CLEANUP
-- Functionality: Delete any game sessions that were flagged as suspicious/cheating.
-- Concepts Covered: DELETE, WHERE
-- ==============================================================================
DELETE FROM Game_Sessions 
WHERE status = 'REJECTED_SUSPICIOUS';

-- ==============================================================================
-- Q4. STUDENT DIRECTORY SEARCH
-- Functionality: Find all students whose names start with 'A' (e.g., Ahsan, Ayesha).
-- Concepts Covered: SELECT, WHERE, LIKE
-- ==============================================================================
SELECT student_id, roll_number, full_name, current_balance
FROM Students
WHERE full_name LIKE 'A%';

-- ==============================================================================
-- Q5. BOOKSHOP REVENUE CALCULATION
-- Functionality: Calculate the total revenue ever generated by the Bookshop.
-- Concepts Covered: SELECT, SUM
-- ==============================================================================
SELECT SUM(total_amount) AS total_bookshop_revenue
FROM Bookshop_Orders
WHERE status = 'COMPLETED';

-- ==============================================================================
-- Q6. E-SPORTS GAME PERFORMANCE
-- Functionality: Find the average cash earned by students per game, ranked highest to lowest.
-- Concepts Covered: AVG, GROUP BY, ORDER BY, INNER JOIN
-- ==============================================================================
SELECT 
    g.game_name, 
    AVG(gs.cash_earned) AS average_cash_payout
FROM E_Sports_Games g
JOIN Game_Sessions gs ON g.game_id = gs.game_id
GROUP BY g.game_name
ORDER BY average_cash_payout DESC;

-- ==============================================================================
-- Q7. CAFETERIA VIP SPENDERS
-- Functionality: Identify students who have spent strictly more than 400 total in the cafeteria.
-- Concepts Covered: SUM, GROUP BY, HAVING, INNER JOIN
-- ==============================================================================
SELECT 
    s.full_name, 
    SUM(co.total_amount) AS total_spent
FROM Students s
JOIN Cafeteria_Orders co ON s.student_id = co.student_id
GROUP BY s.full_name
HAVING SUM(co.total_amount) > 400.00;

-- ==============================================================================
-- Q8. STUDENT GAMING ENGAGEMENT
-- Functionality: List all students and their game sessions. Must include students who haven't played yet.
-- Concepts Covered: LEFT JOIN, ORDER BY
-- ==============================================================================
SELECT 
    s.full_name, 
    gs.raw_score, 
    gs.cash_earned
FROM Students s
LEFT JOIN Game_Sessions gs ON s.student_id = gs.student_id
ORDER BY s.full_name ASC;

-- ==============================================================================
-- Q9. CAFETERIA INVENTORY POPULARITY
-- Functionality: List all cafeteria items and their order quantities. Must include items never ordered (e.g., Samosa).
-- Concepts Covered: RIGHT JOIN
-- ==============================================================================
SELECT 
    ci.item_name, 
    cod.quantity_purchased
FROM Cafeteria_Order_Details cod
RIGHT JOIN Cafeteria_Items ci ON cod.item_id = ci.item_id;

-- ==============================================================================
-- Q10. COMPLETE LEDGER AUDIT
-- Functionality: Show a full alignment of students and their wallet ledger entries. Includes students with no entries, and potential ledger anomalies.
-- Concepts Covered: FULL OUTER JOIN
-- ==============================================================================
SELECT 
    s.full_name, 
    wl.transaction_type, 
    wl.amount
FROM Students s
FULL OUTER JOIN Wallet_Ledger wl ON s.student_id = wl.student_id;

-- ==============================================================================
-- Q11. THE RICHEST STUDENT
-- Functionality: Find the profile of the student who currently has the absolute highest balance.
-- Concepts Covered: Sub/Nested Query
-- ==============================================================================
SELECT roll_number, full_name, current_balance 
FROM Students 
WHERE current_balance = (
    SELECT MAX(current_balance) 
    FROM Students
);

-- ==============================================================================
-- Q12. CROSS-MODULE ENGAGEMENT (GAMERS WHO EAT)
-- Functionality: Find the roll numbers of students who BOTH play E-Sports AND buy food from the Cafeteria.
-- Concepts Covered: INTERSECT
-- ==============================================================================
SELECT student_id FROM Game_Sessions
INTERSECT
SELECT student_id FROM Cafeteria_Orders;

-- ==============================================================================
-- Q13. THE NERD DEMOGRAPHIC (STUDY, NO GAMES)
-- Functionality: Find the roll numbers of students who buy from the Bookshop but have NEVER played an E-Sports game.
-- Concepts Covered: EXCEPT
-- ==============================================================================
SELECT student_id FROM Bookshop_Orders
EXCEPT
SELECT student_id FROM Game_Sessions;

-- ==============================================================================
-- Q14. UNIFIED CAMPUS INVENTORY
-- Functionality: Generate a single master catalog list combining items from both the Cafeteria and the Bookshop.
-- Concepts Covered: UNION
-- ==============================================================================
SELECT item_name AS 'Item Name', category AS 'Department', price 
FROM Cafeteria_Items
UNION
SELECT item_name, item_category, price 
FROM Bookshop_Items;

-- ==============================================================================
-- Q15. THE WHALE GAMER ANALYSIS (COMPLEX QUERY)
-- Functionality: Find high-performing gamers whose personal average game earnings are strictly higher than the overall university's average game earnings.
-- Concepts Covered: Nested Subqueries, Aggregation, INNER JOIN
-- ==============================================================================
SELECT 
    s.full_name, 
    AVG(gs.cash_earned) AS student_avg_earnings
FROM Students s
JOIN Game_Sessions gs ON s.student_id = gs.student_id
GROUP BY s.full_name
HAVING AVG(gs.cash_earned) > (
    SELECT AVG(cash_earned) 
    FROM Game_Sessions
);





